from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
import datetime

def generate_rti(scheme: dict, output_path: str = "RTI_Application.pdf"):
    """
    Auto-generates a pre-filled RTI application PDF for a black-flagged scheme.
    Citizen just downloads, signs, and submits.
    """

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=25*mm, rightMargin=25*mm,
        topMargin=20*mm, bottomMargin=20*mm
    )
    W = A4[0] - 50*mm
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle("title", fontSize=14, fontName="Helvetica-Bold",
        alignment=TA_CENTER, spaceAfter=4)
    subtitle_style = ParagraphStyle("sub", fontSize=11, fontName="Helvetica-Bold",
        alignment=TA_CENTER, spaceAfter=2)
    body_style = ParagraphStyle("body", fontSize=10.5, fontName="Helvetica",
        leading=16, spaceAfter=6, alignment=TA_JUSTIFY)
    label_style = ParagraphStyle("label", fontSize=10, fontName="Helvetica-Bold",
        leading=14, spaceAfter=2)
    field_style = ParagraphStyle("field", fontSize=10.5, fontName="Helvetica",
        leading=14, spaceAfter=8)
    red_style = ParagraphStyle("red", fontSize=11, fontName="Helvetica-Bold",
        textColor=colors.red, alignment=TA_CENTER, spaceAfter=6)
    small_style = ParagraphStyle("small", fontSize=9, fontName="Helvetica",
        textColor=colors.grey, leading=12)

    story = []
    today = datetime.date.today().strftime("%d %B %Y")

    # ── HEADER ────────────────────────────────────────────────────────────────
    story.append(Paragraph("APPLICATION UNDER THE RIGHT TO INFORMATION ACT, 2005", title_style))
    story.append(Paragraph("Section 6(1) — Request for Information", subtitle_style))
    story.append(Spacer(1, 3*mm))
    story.append(HRFlowable(width=W, thickness=1.5, color=colors.black))
    story.append(Spacer(1, 3*mm))

    # AUTO-GENERATED STAMP
    stamp = Table([[Paragraph(
        "AUTO-GENERATED BY SCHEME GATI — BLACK FLAG TRIGGERED",
        ParagraphStyle("stamp", fontSize=9, fontName="Helvetica-Bold",
            textColor=colors.white, alignment=TA_CENTER)
    )]], colWidths=[W])
    stamp.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,-1), colors.black),
        ("TOPPADDING", (0,0), (-1,-1), 5),
        ("BOTTOMPADDING", (0,0), (-1,-1), 5),
    ]))
    story.append(stamp)
    story.append(Spacer(1, 5*mm))

    # ── TO SECTION ────────────────────────────────────────────────────────────
    story.append(Paragraph("To,", label_style))
    story.append(Paragraph("The Public Information Officer (PIO),", field_style))
    story.append(Paragraph(f"{scheme['department']},", field_style))
    story.append(Paragraph(f"{scheme['district']} District, {scheme['state']}.", field_style))
    story.append(Spacer(1, 3*mm))

    story.append(Paragraph(f"Date: {today}", label_style))
    story.append(Spacer(1, 3*mm))

    story.append(Paragraph("Subject: Request for Information regarding delayed government scheme under RTI Act 2005", label_style))
    story.append(HRFlowable(width=W, thickness=0.5, color=colors.grey))
    story.append(Spacer(1, 3*mm))

    # ── SCHEME DETAILS TABLE ──────────────────────────────────────────────────
    story.append(Paragraph("SCHEME DETAILS (Auto-filled by Scheme Gati):", label_style))
    story.append(Spacer(1, 2*mm))

    details_data = [
        ["Scheme Name", scheme["name"]],
        ["Scheme ID / Code", scheme["scheme_id"]],
        ["Ward / Location", scheme["ward"]],
        ["Contractor Name", scheme["contractor"]],
        ["Sanctioned Budget", f"₹ {scheme['budget']}"],
        ["Funds Released to Contractor", f"₹ {scheme['funds_released']}"],
        ["Official Start Date", scheme["start_date"]],
        ["Official Deadline", scheme["deadline"]],
        ["Current Status", f"STALLED — {scheme['delay_days']} days delayed"],
        ["Last Recorded Activity", f"{scheme['last_activity_days']} days ago"],
        ["Citizen Reports Filed", str(scheme["citizen_reports"])],
        ["Flag Status", "⚫ BLACK FLAG — Auto-escalated by Scheme Gati"],
    ]

    details_table = Table(details_data, colWidths=[W*0.38, W*0.62])
    details_table.setStyle(TableStyle([
        ("FONTNAME",       (0,0), (0,-1), "Helvetica-Bold"),
        ("FONTNAME",       (1,0), (1,-1), "Helvetica"),
        ("FONTSIZE",       (0,0), (-1,-1), 10),
        ("BACKGROUND",     (0,0), (0,-1), colors.HexColor("#F5F5F5")),
        ("BACKGROUND",     (1,9), (1,9),  colors.HexColor("#FFF3CD")),
        ("BACKGROUND",     (1,11),(1,11), colors.HexColor("#FFE0E0")),
        ("GRID",           (0,0), (-1,-1), 0.5, colors.grey),
        ("TOPPADDING",     (0,0), (-1,-1), 5),
        ("BOTTOMPADDING",  (0,0), (-1,-1), 5),
        ("LEFTPADDING",    (0,0), (-1,-1), 8),
        ("RIGHTPADDING",   (0,0), (-1,-1), 8),
        ("VALIGN",         (0,0), (-1,-1), "MIDDLE"),
    ]))
    story.append(details_table)
    story.append(Spacer(1, 5*mm))

    # ── INFORMATION REQUESTED ─────────────────────────────────────────────────
    story.append(Paragraph("INFORMATION REQUESTED:", label_style))
    story.append(Spacer(1, 2*mm))

    requests = [
        f"1. Complete details of funds released to {scheme['contractor']} for the scheme '{scheme['name']}', including dates, amounts, and milestones for which payment was made.",
        f"2. The current physical status of work at the scheme site as verified by any government officer.",
        f"3. Reasons for the delay of {scheme['delay_days']} days beyond the official deadline of {scheme['deadline']}.",
        f"4. Action taken or proposed against {scheme['contractor']} for abandonment of work after receiving funds.",
        f"5. Name and designation of the officer responsible for monitoring this scheme.",
        f"6. Copies of all inspection reports filed by field engineers for this scheme since {scheme['start_date']}.",
        f"7. Whether any show cause notice or penalty has been issued to the contractor. If yes, a copy of the same.",
    ]

    for req in requests:
        story.append(Paragraph(req, body_style))

    story.append(Spacer(1, 5*mm))

    # ── LEGAL BASIS ───────────────────────────────────────────────────────────
    story.append(HRFlowable(width=W, thickness=0.5, color=colors.grey))
    story.append(Spacer(1, 3*mm))
    story.append(Paragraph(
        "This application is filed under Section 6(1) of the Right to Information Act, 2005. "
        "As per Section 7(1) of the RTI Act, the information is requested to be provided within "
        "<b>30 days</b> of receipt of this application. The prescribed fee of ₹10 is enclosed "
        "as Indian Postal Order / Court Fee Stamp.",
        body_style
    ))
    story.append(Spacer(1, 5*mm))

    # ── SIGNATURE BLOCK ───────────────────────────────────────────────────────
    sig_data = [
        ["Applicant Name:", "______________________________"],
        ["Address:",        "______________________________"],
        ["",                "______________________________"],
        ["Mobile Number:",  "______________________________"],
        ["Email (optional):","______________________________"],
        ["Date:",           today],
        ["Signature:",      "______________________________"],
    ]
    sig_table = Table(sig_data, colWidths=[W*0.35, W*0.65])
    sig_table.setStyle(TableStyle([
        ("FONTNAME",      (0,0), (0,-1), "Helvetica-Bold"),
        ("FONTNAME",      (1,0), (1,-1), "Helvetica"),
        ("FONTSIZE",      (0,0), (-1,-1), 10),
        ("TOPPADDING",    (0,0), (-1,-1), 5),
        ("BOTTOMPADDING", (0,0), (-1,-1), 5),
        ("LEFTPADDING",   (0,0), (-1,-1), 0),
        ("VALIGN",        (0,0), (-1,-1), "MIDDLE"),
    ]))
    story.append(sig_table)
    story.append(Spacer(1, 5*mm))

    # ── FOOTER ────────────────────────────────────────────────────────────────
    story.append(HRFlowable(width=W, thickness=1, color=colors.black))
    story.append(Spacer(1, 2*mm))
    story.append(Paragraph(
        "This document was auto-generated by Scheme Gati (schemegati.gov.in) when this scheme "
        "triggered a BLACK FLAG — stalled for 30+ days with funds released and zero activity. "
        "Scheme Gati is a real-time government scheme monitoring platform.",
        small_style
    ))

    doc.build(story)
    print(f"  RTI PDF generated: {output_path}")


# ── DEMO ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    demo_scheme = {
        "name":               "Ward 2 — Grid Modernization Phase II",
        "scheme_id":          "UP/KNP/WARD2/2024/0047",
        "ward":               "Ward 2 — Sector 07, Kanpur Urban",
        "department":         "Department of Urban Development & Smart City",
        "district":           "Kanpur",
        "state":              "Uttar Pradesh",
        "contractor":         "M/S Shakti Infrastructure Pvt. Ltd.",
        "budget":             "14,28,00,000",
        "funds_released":     "9,80,00,000",
        "start_date":         "12 March 2024",
        "deadline":           "10 September 2024",
        "delay_days":         42,
        "last_activity_days": 35,
        "citizen_reports":    11,
    }

    print("\n  Generating RTI PDF for black-flagged scheme...")
    generate_rti(demo_scheme, "RTI_SchemeGati_Demo.pdf")
    print("  Open RTI_SchemeGati_Demo.pdf to see the output.\n")
